<div class="pickup-title-container">
    <div class="title-container">
        <div class="step-title" data-role="title">Do you want to Click & Collect?</div>
        <span>Rougham, Bury St Edmunds. IP30 9XA</span>
    </div>
    <div class="free">
            <strong>FREE</strong>
    </div>
</div>
<div id="checkout-step-pas" class="pas-use step-content" data-role="content">
    <div class="control">
        <input type='radio' id="pas-yes" <?php if ($block->getStorePickupActivatedDefault() === "1") {
            echo 'checked="checked"';
} ?> onclick="PickupAtStore.showPickupAtStore(true);PickupAtStore.updateShippingMethod();" name='pickupatstore' value='1'/>
        <span><?php echo __("Yes"); ?></span>
    </div>
    <div class="control">
        <input type='radio' id="pas-no" <?php if ($block->getStorePickupActivatedDefault() !== "1") {
            echo 'checked="checked"';
} ?> onclick="PickupAtStore.showPickupAtStore(false);jQuery(jQuery('[name^=ko_unique_]')[0]).trigger('click');"  name='pickupatstore' value='0'/>
        <span><?php echo __("No"); ?></span>
    </div>
</div>
