<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/*  @codingStandardsIgnoreFile */

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    $iconDir = $this->getURL("pub/media/allergens");/* .'\allergens'; */

    $discontinued = $iconDir.'discontinued'; 


    $contain = 'Yes';
    $notcontain = 'No';

    $containArray = [];
    $count = 0;

    $discontinuedvalue = $_product->getResource()->getAttribute('discontinued')->getFrontend()->getValue($_product);

    switch ($discontinuedvalue) {
        case $contain:
            $containArray[$count]['name'] = $_product->getResource()->getAttribute('discontinued')->getStoreLabel($_product);
            $containArray[$count]['image'] = $discontinued."_red";
            break;
        default:
            $discontinued.="";
    };

   ?>

<div class="icon-wrapper">
    <?php if(count($containArray) > 0) { ?>
	<div class="allert-section">
     <!--   <h3>Product Allerts :</h3> -->
        <div class="allert-section-icons">
        <?php foreach($containArray as $contain) { ?>
            <div class="content">
                <img src="<?= $contain['image'].'.svg'; ?>" style="width: 48px;">
                <span class="allert-span"><?= $contain['name']; ?></span>
            </div>
        <?php } ?>		
	</div>
        </div>
    <?php } ?>

</div>