<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2023 Amasty (https://www.amasty.com)
 * @package Shop by Brand for Magento 2
 */
use Magento\Framework\App\Action\Action;
/**
 * @var \Amasty\ShopbyBrand\Block\Catalog\Product\ProductList\MoreFrom $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php
$class = 'amshopby-morefrom';
$image = 'am_brand_more_from_image';
$title = $block->getTitle();
$items = $block->getItems();

$showAddTo = true;
$showCart = true;
$templateType = null;
$description = false;

$productListObj= $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
echo $productListObj->getMyCustomMethod();

?>


<div class="block <?= /* @noEscape */ $class ?>">
    <div class="block-title title">
        <strong id="block-<?= /* @noEscape */ $class ?>-heading" role="heading" aria-level="2">
            <?= $escaper->escapeHtml($title) ?>
        </strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= /* @noEscape */ $class ?>-heading">
        <div class="products wrapper grid products-grid products-morefrom">
            <ol class="products list items product-items ">
                <?php foreach ($items as $item): ?>
                    <li class="item product product-item">

                        <div class="product-item-info">
                            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                            <a href="<?= $productUrl = $escaper->escapeUrl($block->getProductUrl($item)) ?>"
                               aria-label="<?= $escaper->escapeHtmlAttr(__($image)); ?>"
                               class="product photo product-item-photo">
                                <?= $block->getImage($item, $image)->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <p class="product-sku"><?php echo $item->getSku()?></p>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       title="<?= $escaper->escapeHtml($item->getName()) ?>"
                                       href="<?= /* @noEscape */ $productUrl ?>">
                                        <?= $escaper->escapeHtml($item->getName()) ?>
                                    </a>
                                </strong>
                                <?php 
                                ?>


                                <?= /* @noEscape */ $block->getProductPrice($item) ?>

                                <?php if ($showAddTo || $showCart): ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($item->isSaleable()): ?>
                                                <?php $postParams = $productListObj->getAddToCartPostParams($item); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $productListObj->escapeHtml($item->getSku()) ?>" action="<?= $productListObj->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $productListObj->getBlockHtml('formkey') ?>
                                                        <div class="control morefrom">
                                                            <div class="custom-qty reduced"><button type="button" class="more-from-btn-qty minus"><span class="mbi mbi-minus">-</span></button></div>
                                                                <input name="qty" id="qty" value="1" title="<?= /* @escapeNotVerified */ __('Qty') ?>" class="input-text qty"/>
                                                            <div class="custom-qty increase"><button type="button" class="more-from-btn-qty plus"><span class="mbi mbi-plus">+</span></button></div>
                                                        </div>
                                                        <button type="submit"
                                                                title="<?= $productListObj->escapeHtml(__('Add')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= $productListObj->escapeHtml(__('Add')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($item->getIsSalable()): ?>
                                                        <div class="stock available">
                                                            <span><?= /* @noEscape */ __('In stock') ?></span>
                                                        </div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable">
                                                            <span><?= /* @noEscape */ __('Out of stock') ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <div data-role="add-to-links" class="actions-secondary">
                                                    <?php if ($block->getWishlistHelper()->isAllow()): ?>
                                                        <a href="#"
                                                           class="action towishlist"
                                                           title="<?= $escaper->escapeHtml(__('Add to Wish List')); ?>"
                                                           aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')); ?>"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($item); ?>'
                                                           data-action="add-to-wishlist"
                                                           role="button">
                                                            <span><?= /* @noEscape */ __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <a href="#"
                                                       class="action tocompare"
                                                       title="<?= $escaper->escapeHtml(__('Add to Compare')); ?>"
                                                       aria-label="<?= $escaper->escapeHtml(__('Add to Compare')); ?>"
                                                       data-post='<?= /* @noEscape */ $block->getCompareHelper()->getPostDataParams($item); ?>'
                                                       role="button">
                                                        <span><?= /* @noEscape */ __('Add to Compare') ?></span>
                                                    </a>
                                                </div>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ($showAddTo && ($addToBlock = $block->getChildBlock('addto'))): ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <?= /* @noEscape */ $addToBlock->setProduct($item)->getChildHtml(); ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<script>
require(['jquery', 'jquery/ui', 'slick'], function($) {
    $(document).ready(function() {
    function mobileOnlySlider($slidername, $breakpoint) {
            var slider = jQuery($slidername);
            var settings = {
                mobileFirst: true,
                dots: false,
                arrows: false,
                slidesToShow: 1.5,
                slidesToScroll: 1,
                autoplay: false,
                infinite: false,
                responsive: [
                    {
                        breakpoint: $breakpoint,
                        settings: "unslick",
                        slidesToShow: 1.5,
                        slidesToScroll: 1,
                    }
                ]
            };

            slider.slick(settings);
            jQuery(window).on("resize", function () {
                if (jQuery(window).width() > $breakpoint) {
                    return;
                }
                if (!slider.hasClass("slick-initialized")) {
                    return slider.slick(settings);
                }
            });
        }

        mobileOnlySlider(".products-morefrom .product-items", 767);

          // qty increment decrement    
          var newVal,
            inrement = 1;
        jQuery(".more-from-btn-qty").click(function () {
            var button = jQuery(this),
                oldValue = button.closest('.control').find(".input-text.qty").val();
            if (button.hasClass('plus')) {
                newVal = parseFloat(oldValue) + inrement;
                button.closest('.control').find(".input-text.qty").val(newVal);
                button.closest('.control').find(".input-text.qty").attr('value',newVal);
                jQuery('.cart-item.qty').trigger("change");
            } else {
                if (oldValue > 1) {
                    newVal = parseFloat(oldValue) - inrement;
                    button.closest('.control').find(".input-text.qty").val(newVal);
                    button.closest('.control').find(".input-text.qty").attr('value',newVal);
                    jQuery('.cart-item.qty').trigger("change");
                } 
            }
          

        });
 

    })
})
</script>