<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php 
$blockObj= $block->getLayout()->createBlock('Amasty\Shopby\Block\Navigation\State');
$filters = $blockObj->getActiveFilters();
// $value = [];
$item=[];
foreach ($filters as $filter) {
    $name=$filter->getName();
    if(key_exists($name,$item)){
        $value=$item[$name];
        $value++;
        $item[$name]=$value;
    }
    else{
        $item[$name]=1;
    }
    
}
?>
<?php if ($block->canShowBlock()) : ?>
    <div class="block filter filter-main">
        <div class="block-title filter-title">
            <strong><?= $block->escapeHtml(__('Filter by')) ?></strong>
        </div>

        <div class="block-content filter-content filter-main-container">
            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if (!$wrapOptions) : ?>
                    <dl class="filter-options" id="narrow-by-list">
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if ($filter->getItemsCount()) : ?>
                        <dt role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?>
                        <?php if(key_exists($filter->getName(),$item)){
                            $count= $item[$filter->getName()]; ?>
                        <span class="filter-count"> (<?=$count ?>)</span>    
                        <?php }?>
                        </dt>
                        <dd class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
